-- ============================================================
-- NOWPDP Disability Awareness Survey — Supabase Schema
-- Run this in your Supabase SQL Editor (in order)
-- ============================================================

-- 1. Create responses table
CREATE TABLE responses (
  id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  age         TEXT,
  gender      TEXT,
  education   TEXT,
  q1          TEXT,
  q2          TEXT,
  q3          TEXT,
  q4          TEXT,
  q5          TEXT,
  q6          TEXT,
  q7          TEXT,
  q8          TEXT,
  q9          TEXT,
  q10         TEXT,
  q11         TEXT,
  q12         TEXT,
  submitted_at TIMESTAMPTZ DEFAULT NOW()
);

-- 2. Create admins table
CREATE TABLE admins (
  id       BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  username TEXT UNIQUE NOT NULL,
  password TEXT NOT NULL
);

-- 3. Insert your admin credentials (CHANGE THESE!)
INSERT INTO admins (username, password) VALUES
  ('admin', 'nowpdp_admin_2025'),
  ('nowpdp', 'change_this_password');

-- 4. Enable Row Level Security
ALTER TABLE responses ENABLE ROW LEVEL SECURITY;
ALTER TABLE admins    ENABLE ROW LEVEL SECURITY;

-- 5. Policies for responses table
CREATE POLICY "responses_insert" ON responses
  FOR INSERT TO anon, authenticated
  WITH CHECK (true);

CREATE POLICY "responses_select" ON responses
  FOR SELECT TO anon, authenticated
  USING (true);

-- 6. Policy for admins table
CREATE POLICY "admins_select" ON admins
  FOR SELECT TO anon, authenticated
  USING (true);
